[project]
name = "careerpulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "ipython>=9.10.0",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "passlib[bcrypt]>=1.7.4",
    "pdfplumber>=0.11.9",
    "prefect>=3.6.18",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.13.1",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "qdrant-client>=1.17.0",
    "scrapy>=2.14.1",
    "slowapi>=0.1.9",
    "spacy>=3.8.11",
    "sqlalchemy>=2.0.46",
    "sympy>=1.14.0",
    "uvicorn>=0.41.0",
]
